[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"


[project]
name = "si_ref_point"
version = "1.0b"
description = "SI reference point generation scripts and source data"
authors = [
    {name = "Stuart Chalk", email =  "n00002621@unf.edu"},
    {name = "Gregor Dudle", email =  "gregor.dudle@ost.ch"},
    {name = "Max Gruber", email = "maximilian.gruber@ptb.de"},
    {name = "Jean-Laurent Hippolyte", email = "jean-laurent.hippolyte@npl.co.uk"},
    {name = "Frédéric Meynadier", email = "Frederic.Meynadier@bipm.org"},
    {name = "Janet Miles", email = "jmiles@bipm.org"}
] 
readme = "Readme.md"
requires-python = ">=3.11"
dependencies = [
    "rdflib",
    "Jinja2",
    "PyYAML",
    "uvicorn",
    "ontospy",
    "owlready2",
    "owlrl",
    "fastapi",
    "pydantic>=1.10,<2.0",
    "pyshacl",
    "gitpython"
]


[project.urls]
repository = "https://github.com/TheBIPM/SI-Reference-Point-2023"


[project.scripts]
generate_turtle_files = "si_ref_point.main:main"
launch_si_test_api = "si_ref_point.test_api.launch_api:main"


